### ISSUE TITLE
Should it be Pack.class?

### ISSUE THREAD

**Issue by red55** [3esi/dotnet-plugin#2]
https://github.com/3esi/dotnet-plugin/blob/f11c37fc9ea12165162e8ca1a4d56758dcce5907/src/main/java/net/karlmartens/dotnet/Pack.java#L16

**Comment by karlmartens** [comment]
This line should read ...getLogger(Pack.class);

**Comment by karlmartens** [comment]
### Issue
A cut and paste issue that would have caused debug logging to go against the wrong category. 
Resolved the issue in commit 33f326185deb6b723657ac4f202013fbf9a46ea6
### Impact
* Minor
### Version
* Will be available in the next version 0.2.19
